# Generated by Django 5.0 on 2024-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=100, unique=True)),
                ('Image', models.ImageField(upload_to='employee_images/')),
            ],
        ),
    ]
